### ISSUE TITLE
Get "file not found" after running lando start 

### ISSUE THREAD

**Issue by rick02840** [thinktandem/migration-webinar#2]
Hi John,
Thanks for the webinar yesterday!
I get "file not found" after `lando start` when I go here:   http://migration-webinar.lndo.site.
Other URLs get "This site can’t be reached". 
Lando version:  v3.0.0-rrc.1
If any advice, would appreciate it.  I can post `lando info` output if that helps. 
Thanks,
Rick 

Your app has started up correctly.
Here are some vitals:

 NAME                  migration-webinar
 LOCATION              /Users/rick/Sites/_learning/drupal/migration/tandem/migration-webinar
 SERVICES              appserver_nginx, appserver, database, d7db
 APPSERVER_NGINX URLS  https://localhost:32775
                       http://localhost:32776
                       http://migration-webinar.lndo.site
                       https://migration-webinar.lndo.site

**Comment by rick02840** [comment]
Oh geez, never mind, forgot `composer install`   ;-)

**Comment by rick02840** [comment]
Update (in case anyone else needs this):
- updated to Lando 3.0.1
- did `lando destroy`
- did `lando start `
- did `lando composer install`
now I get the Drupal install page

**Comment by labboy0276** [comment]
Hi @rick02840 I had commented out the composer install option in my lando yaml since I was rebuilding a lot and didnt want to wait.  

I put that back in so you dont need to run composer install on build

**Comment by rick02840** [comment]
Ah OK cool.  I was not familiar with`.lando.base.yml`  just `.lando.yml `.  Looks like it more or less does the same thing.

**Comment by labboy0276** [comment]
@rick02840 Yeah it is a way to have various lando files based on your environment basically.  The base is the defaults for all that can be overridden if need be: https://docs.lando.dev/config/lando.html#base-file
